### ISSUE TITLE
How to include collections in a graph that is already created?

### ISSUE THREAD

**Issue by melonista** [tariqdaouda/pyArango#75]
Hey there,

For example I want to add "Humans4" to the graph so I update the EdgeDefinition:

    class social3(Graph) :

        _edgeDefinitions = (EdgeDefinition ('siblin4',
                                        fromCollections = ["female", "male", "Humans4"],
                                        toCollections = ["female", "male", "Humans4"]),)
        _orphanedCollections = []

Then I load the graph and indeed it seems it has been updated::

    g = db.graphs['social3']
    g.definitions

    {'siblin4': <ArangoED>{'collection': 'siblin4', 'from': ['female', 'male', 'Humans4'], 'to': ['female', 'male', 'Humans4']}}

But still:

    g.createVertex('Humans4', {'name':'pepe'})

raises:

    ---------------------------------------------------------------------------
    CreationError                             Traceback (most recent call last)
    <ipython-input-29-f3363e33b4a4> in <module>()
    ----> 1 g.createVertex('Humans4', {'name':'pepe'})
    
    /Users/k/3virtualenvs/ENV31/lib/python3.6/site-packages/pyArango/graph.py in     createVertex(self, collectionName, docAttributes, waitForSync)
        127             return self.database[collectionName][data["vertex"]["_key"]]
        128 
    --> 129         raise CreationError("Unable to create vertice, %s" % data["errorMessage"], data)
        130 
        131     def deleteVertex(self, document, waitForSync = False) :

    CreationError: Unable to create vertice, collection not found. Errors: {'error': True, 'errorNum': 1203, 'errorMessage': 'collection not found', 'code': 404}

Also, similarly, I'd like to know how to modify Document definitions (validators, etc).

Thanks!

**Comment by tariqdaouda** [comment]
Hi @melonista,

Did you try to explicitly declare the Human4 as a class of type Edges? That should fix the problem.
It's easy to change document definition, you just need to modify the class definition and append/remove any validator you want:

`_fields = {
        'name' : Field(validators = [VAL.NotNull(), String_val()]),
        'anything' : Field(),
        'species' : Field(validators = [VAL.NotNull(), VAL.Length(5, 15), String_val()])
      }`

**Comment by cresteban** [comment]
Thanks for the reply @tariqdaouda.

I had created Humans4 as the other collections:

`db.createCollection('Humans4', name="Humans4")`

I am now trying:

    h = db.createCollection('Humans6', name="Humans6")
    h.documentClass = COL.Edges

But I still get the same error. Could you please let me know which is the right way to do it or where in the docs can I find it? Thanks!

**Comment by melonista** [comment]
Thanks for the reply @tariqdaouda.

I had created Humans4 as the other collections:

    db.createCollection('Humans4', name="Humans4")

I am now trying:


    h = db.createCollection('Humans4', name="Humans4")
    h.documentClass = COL.Edges

But I still get the same error. Could you please let me know which is the right way to do it or where in the docs can I find it? Thanks!

**Comment by tariqdaouda** [comment]
Do you mean creating de Edges collection [as shown in the readme?](https://github.com/tariqdaouda/pyArango#creating-edges). If that is is the case could paste in the full minimal code that produces the error? I'll check it, it might be a bug.

**Comment by cresteban** [comment]
Hi again, 

Since the semantics of my initial example were awful, here I put a more clear example. 

What I want to do is to add a new vertex collection to an existing graph. The example is divided in 3 scripts.

First I create the graph "people" with "americans" and "germans":

    # creates people graph
    # vertices: american, german
    # edges: friends

    import pyArango.collection as COL
    import pyArango.validation as VAL
    from pyArango.theExceptions import ValidationError
    from pyArango.collection import Edges
    from pyArango.connection import Connection
    from pyArango.collection import Field
    from pyArango.graph import Graph, EdgeDefinition


    conn = Connection(username="root", password="")
    db = conn["test"]

    class String_val(VAL.Validator) :
        def validate(self, value) :
            if type(value) != str :
                raise ValidationError("Field value must be a string")
            return True

    class americans(COL.Collection) :

        _validation = {
            'on_save' : True,
            'on_set' : True,
            'allow_foreign_fields' : False # allow fields that are not part of the schema
        }

        _fields = {
            'name' : Field(validators = [VAL.NotNull(), String_val()]),
            'anything' : Field()
        }
        
        
    class germans(COL.Collection) :
        _fields = {
            'name' : Field()
        }
        
        
    class friends(Edges) :

        _validation = {
            'on_save' : False,
            'on_set' : False,
            'allow_foreign_fields' : True # allow fields that are not part of the schema
        }

        _fields = {
            'length' : Field(),
        }

    collection1 = db.createCollection('americans')
    collection2 = db.createCollection('germans')
    collection3 = db.createCollection('friends')

    class people(Graph) :

        _edgeDefinitions = (EdgeDefinition ('friends',
                                            fromCollections = ["americans", "germans"],
                                            toCollections = ["americans", "germans"]),)
        _orphanedCollections = []
        
    g = db.createGraph("people")

Then I add some samples:

    # creates some vertices

    import pyArango.collection as COL
    import pyArango.validation as VAL
    from pyArango.theExceptions import ValidationError
    from pyArango.collection import Edges
    from pyArango.connection import Connection
    from pyArango.collection import Field

    conn = Connection(username="root", password="")
    db = conn["test"]

    g = db.graphs['people']

    g = db.graphs['people']
    a = g.createVertex('americans', {'name':'John'})
    b = g.createVertex('germans', {'name':'Hans', 'gender':'male'})
    g.link('friends', a, b, {"length": 2})


Now the point is that I want to add a new collection of vertices to the graph "australians". How do I do that? I tried: 

    # now I want to add a new vertex collection named "australian" to the "people" graph

    import pyArango.collection as COL
    import pyArango.validation as VAL
    from pyArango.theExceptions import ValidationError
    from pyArango.collection import Edges
    from pyArango.connection import Connection
    from pyArango.collection import Field
    from pyArango.graph import Graph, EdgeDefinition

    conn = Connection(username="root", password="")
    db = conn["test"]

    class String_val(VAL.Validator) :
        def validate(self, value) :
            if type(value) != str :
                raise ValidationError("Field value must be a string")
            return True

    class americans(COL.Collection) :

        _validation = {
            'on_save' : False,
            'on_set' : False,
            'allow_foreign_fields' : True # allow fields that are not part of the schema
        }

        _fields = {
            'name' : Field(validators = [VAL.NotNull(), String_val()]),
            'anything' : Field()
        }
        
        
    class germans(COL.Collection) :
        _fields = {
            'name' : Field()
        }
        
        
    class friends(Edges) :

        _validation = {
            'on_save' : False,
            'on_set' : False,
            'allow_foreign_fields' : True # allow fields that are not part of the schema
        }

        _fields = {
            'length' : Field(),
        }

    class australians(COL.Collection) :
        _fields = {
            'name' : Field()
        }
      
    class people(Graph) :

        _edgeDefinitions = (EdgeDefinition ('friends',
                                            fromCollections = ["americans", "germans", "australians"],
                                            toCollections = ["americans", "germans", "australians"]),)
        _orphanedCollections = []
        
    collection4 = db.createCollection('australians')
    g = db.graphs['people']
    g.createVertex('australians', {'name':'John'})

But it raises an error:

    ---------------------------------------------------------------------------
    CreationError                             Traceback (most recent call last)
    <ipython-input-2-f6fd0f59044c> in <module>()
         64 collection3 = db.createCollection('australians')
         65 g = db.graphs['people']
    ---> 66 g.createVertex('australians', {'name':'John'})

    /Users/k/3virtualenvs/ENV31/lib/python3.6/site-packages/pyArango/graph.py in createVertex(self, collectionName, docAttributes, waitForSync)
        127             return self.database[collectionName][data["vertex"]["_key"]]
        128 
    --> 129         raise CreationError("Unable to create vertice, %s" % data["errorMessage"], data)
        130 
        131     def deleteVertex(self, document, waitForSync = False) :

    CreationError: Unable to create vertice, collection not found. Errors: {'error': True, 'errorNum': 1203, 'errorMessage': 'collection not found', 'code': 404}

So, how do I add a new vertex collection to an existing graph? What am I doing wrong?

Thanks!

**Comment by melonista** [comment]
Hi again, 

Since the semantics of my initial example were awful, here I put a more clear example. 

What I want to do is to add a new vertex collection to an existing graph. The example is divided in 3 scripts.

First I create the graph "people" with "americans" and "germans":

    # creates people graph
    # vertices: american, german
    # edges: friends

    import pyArango.collection as COL
    import pyArango.validation as VAL
    from pyArango.theExceptions import ValidationError
    from pyArango.collection import Edges
    from pyArango.connection import Connection
    from pyArango.collection import Field
    from pyArango.graph import Graph, EdgeDefinition


    conn = Connection(username="root", password="")
    db = conn["test"]

    class String_val(VAL.Validator) :
        def validate(self, value) :
            if type(value) != str :
                raise ValidationError("Field value must be a string")
            return True

    class americans(COL.Collection) :

        _validation = {
            'on_save' : True,
            'on_set' : True,
            'allow_foreign_fields' : False # allow fields that are not part of the schema
        }

        _fields = {
            'name' : Field(validators = [VAL.NotNull(), String_val()]),
            'anything' : Field()
        }
        
        
    class germans(COL.Collection) :
        _fields = {
            'name' : Field()
        }
        
        
    class friends(Edges) :

        _validation = {
            'on_save' : False,
            'on_set' : False,
            'allow_foreign_fields' : True # allow fields that are not part of the schema
        }

        _fields = {
            'length' : Field(),
        }

    collection1 = db.createCollection('americans')
    collection2 = db.createCollection('germans')
    collection3 = db.createCollection('friends')

    class people(Graph) :

        _edgeDefinitions = (EdgeDefinition ('friends',
                                            fromCollections = ["americans", "germans"],
                                            toCollections = ["americans", "germans"]),)
        _orphanedCollections = []
        
    g = db.createGraph("people")

Then I add some samples:

    # creates some vertices

    import pyArango.collection as COL
    import pyArango.validation as VAL
    from pyArango.theExceptions import ValidationError
    from pyArango.collection import Edges
    from pyArango.connection import Connection
    from pyArango.collection import Field

    conn = Connection(username="root", password="")
    db = conn["test"]

    g = db.graphs['people']

    g = db.graphs['people']
    a = g.createVertex('americans', {'name':'John'})
    b = g.createVertex('germans', {'name':'Hans', 'gender':'male'})
    g.link('friends', a, b, {"length": 2})


Now the point is that I want to add a new collection of vertices to the graph "australians". How do I do that? I tried: 

    # now I want to add a new vertex collection named "australian" to the "people" graph

    import pyArango.collection as COL
    import pyArango.validation as VAL
    from pyArango.theExceptions import ValidationError
    from pyArango.collection import Edges
    from pyArango.connection import Connection
    from pyArango.collection import Field
    from pyArango.graph import Graph, EdgeDefinition

    conn = Connection(username="root", password="")
    db = conn["test"]

    class String_val(VAL.Validator) :
        def validate(self, value) :
            if type(value) != str :
                raise ValidationError("Field value must be a string")
            return True

    class americans(COL.Collection) :

        _validation = {
            'on_save' : False,
            'on_set' : False,
            'allow_foreign_fields' : True # allow fields that are not part of the schema
        }

        _fields = {
            'name' : Field(validators = [VAL.NotNull(), String_val()]),
            'anything' : Field()
        }
        
        
    class germans(COL.Collection) :
        _fields = {
            'name' : Field()
        }
        
        
    class friends(Edges) :

        _validation = {
            'on_save' : False,
            'on_set' : False,
            'allow_foreign_fields' : True # allow fields that are not part of the schema
        }

        _fields = {
            'length' : Field(),
        }

    class australians(COL.Collection) :
        _fields = {
            'name' : Field()
        }
      
    class people(Graph) :

        _edgeDefinitions = (EdgeDefinition ('friends',
                                            fromCollections = ["americans", "germans", "australians"],
                                            toCollections = ["americans", "germans", "australians"]),)
        _orphanedCollections = []
        
    collection4 = db.createCollection('australians')
    g = db.graphs['people']
    g.createVertex('australians', {'name':'John'})

But it raises an error:

    ---------------------------------------------------------------------------
    CreationError                             Traceback (most recent call last)
    <ipython-input-2-f6fd0f59044c> in <module>()
         64 collection3 = db.createCollection('australians')
         65 g = db.graphs['people']
    ---> 66 g.createVertex('australians', {'name':'John'})

    /Users/k/3virtualenvs/ENV31/lib/python3.6/site-packages/pyArango/graph.py in createVertex(self, collectionName, docAttributes, waitForSync)
        127             return self.database[collectionName][data["vertex"]["_key"]]
        128 
    --> 129         raise CreationError("Unable to create vertice, %s" % data["errorMessage"], data)
        130 
        131     def deleteVertex(self, document, waitForSync = False) :

    CreationError: Unable to create vertice, collection not found. Errors: {'error': True, 'errorNum': 1203, 'errorMessage': 'collection not found', 'code': 404}

So, how do I add a new vertex collection to an existing graph? What am I doing wrong?

Thanks!

**Comment by tariqdaouda** [comment]
Hi @melonista,

The error comes form ArangoDB not form pyArango. To the best of my knowledge ArangoDB does not support the modification of edges definitions after graph creation. However, you can try to add the new collection to the list of orphaned collections.

Cheers,

**Comment by melonista** [comment]
I see, thanks for your help. I'll ask to the Arango devs just in case.

**Comment by g-LuL** [comment]
Hi,
Is there any news on this ?
I'm trying to update edgeDefinitions on an already created graph too. 
But this graph does not update.
However, i've read this on the arangodb website. 
`arangosh> graph._extendEdgeDefinitions(rel);`
It seems the edgeDefinitions update is possible through arangosh.
Is there a way to do it with pyarango ?

Thanks !
